spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI}

management:
  tracing:
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    root: WARN
    dk.tinker.designer: INFO
