spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

permission-lib:
  auth-service-url: ${AUTH_SERVICE_URL}
  service-api-key: ${PERMISSION_LIB_API_KEY}

management:
  tracing:
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    root: WARN
    dk.tinker.designer: INFO
