spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/designerdb
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.data.mongodb: DEBUG
